// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2qHYzhqIV3XmttaVIYQbjZGA01vcO3M',
    appId: '1:507237477096:web:871db731cfc44fb629b75d',
    messagingSenderId: '507237477096',
    projectId: 'vertical-prototype-70c6c',
    authDomain: 'vertical-prototype-70c6c.firebaseapp.com',
    storageBucket: 'vertical-prototype-70c6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvrjdicgb1-sk32Fb1-LPma5V-qJRkzI0',
    appId: '1:507237477096:android:6103c12cdcc2200929b75d',
    messagingSenderId: '507237477096',
    projectId: 'vertical-prototype-70c6c',
    storageBucket: 'vertical-prototype-70c6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4maOo2cU8wBGCGrGt33c1bHK1zsZBbog',
    appId: '1:507237477096:ios:5a36c98239fa625d29b75d',
    messagingSenderId: '507237477096',
    projectId: 'vertical-prototype-70c6c',
    storageBucket: 'vertical-prototype-70c6c.appspot.com',
    iosClientId: '507237477096-5du47cin6hpol1orq20jaesidsm5cr2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4maOo2cU8wBGCGrGt33c1bHK1zsZBbog',
    appId: '1:507237477096:ios:b620355dcc05a43029b75d',
    messagingSenderId: '507237477096',
    projectId: 'vertical-prototype-70c6c',
    storageBucket: 'vertical-prototype-70c6c.appspot.com',
    iosClientId: '507237477096-5not8v7ksi5ufok3caprkc58nnu36tk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.register.RunnerTests',
  );
}
